//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rescuebots.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rescuebots.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ALL_OPEN {
            get {
                object obj = ResourceManager.GetObject("ALL_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ALL_OPEN1 {
            get {
                object obj = ResourceManager.GetObject("ALL_OPEN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("EAST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("EAST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_SOUTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("EAST_SOUTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_SOUTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("EAST_SOUTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_SOUTH_WEST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("EAST_SOUTH_WEST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_SOUTH_WEST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("EAST_SOUTH_WEST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_TO_SOUTH_IN {
            get {
                object obj = ResourceManager.GetObject("EAST_TO_SOUTH_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_TO_SOUTH_OUT {
            get {
                object obj = ResourceManager.GetObject("EAST_TO_SOUTH_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_TO_WEST_IN {
            get {
                object obj = ResourceManager.GetObject("EAST_TO_WEST_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_TO_WEST_OUT {
            get {
                object obj = ResourceManager.GetObject("EAST_TO_WEST_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_WEST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("EAST_WEST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EAST_WEST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("EAST_WEST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NO_STARTPOSITION_OR_VICTIM {
            get {
                object obj = ResourceManager.GetObject("NO_STARTPOSITION_OR_VICTIM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("NORTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("NORTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_EAST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("NORTH_EAST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_EAST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("NORTH_EAST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_EAST_SOUTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("NORTH_EAST_SOUTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_EAST_SOUTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("NORTH_EAST_SOUTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_SOUTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("NORTH_SOUTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_SOUTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("NORTH_SOUTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_TO_EAST_IN {
            get {
                object obj = ResourceManager.GetObject("NORTH_TO_EAST_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_TO_EAST_OUT {
            get {
                object obj = ResourceManager.GetObject("NORTH_TO_EAST_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_TO_SOUTH_IN {
            get {
                object obj = ResourceManager.GetObject("NORTH_TO_SOUTH_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NORTH_TO_SOUTH_OUT {
            get {
                object obj = ResourceManager.GetObject("NORTH_TO_SOUTH_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NOT_ENTERED_ZONE_IN {
            get {
                object obj = ResourceManager.GetObject("NOT_ENTERED_ZONE_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NOT_ENTERED_ZONE_OUT {
            get {
                object obj = ResourceManager.GetObject("NOT_ENTERED_ZONE_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("SOUTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("SOUTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_TO_WEST_IN {
            get {
                object obj = ResourceManager.GetObject("SOUTH_TO_WEST_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_TO_WEST_OUT {
            get {
                object obj = ResourceManager.GetObject("SOUTH_TO_WEST_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_WEST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("SOUTH_WEST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_WEST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("SOUTH_WEST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_WEST_NORTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("SOUTH_WEST_NORTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SOUTH_WEST_NORTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("SOUTH_WEST_NORTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STARTPOSITION {
            get {
                object obj = ResourceManager.GetObject("STARTPOSITION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VICTIM {
            get {
                object obj = ResourceManager.GetObject("VICTIM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("WEST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("WEST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_NORTH_CLOSED {
            get {
                object obj = ResourceManager.GetObject("WEST_NORTH_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_NORTH_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("WEST_NORTH_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_NORTH_EAST_CLOSED {
            get {
                object obj = ResourceManager.GetObject("WEST_NORTH_EAST_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_NORTH_EAST_CLOSED1 {
            get {
                object obj = ResourceManager.GetObject("WEST_NORTH_EAST_CLOSED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_TO_NORTH_IN {
            get {
                object obj = ResourceManager.GetObject("WEST_TO_NORTH_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEST_TO_NORTH_OUT {
            get {
                object obj = ResourceManager.GetObject("WEST_TO_NORTH_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
